conf: !!python/object:argparse.Namespace
  batch_size: 64
  device: gpu
  finetuned_layers: 1
  lr: 0.001
  max_epochs: 100
  max_text_length: -1
  name: multitask
  num_workers: 12
  optimizer: Adam
  path: models/bert_multitask
  progress_bar: true
  sample: null
  seed: 20
  task_layers: 1
  tokenizer: BERT
model_hparams: {}
model_name: multitask
optimizer_hparams:
  lr: 0.001
optimizer_name: Adam
