#!/bin/bash

# Before being able to download the data, you must register for a Kaggle account setup this account
# Follow the steps on this website: https://github.com/Kaggle/kaggle-api#api-credentials

kaggle competitions download -c learn-ai-bbc
mv learn-ai-bbc.zip Data/
cd Data/
unzip learn-ai-bbc.zip
rm learn-ai-bbc.zip