conf: !!python/object:argparse.Namespace
  batch_size: 1
  device: cpu
  finetuned_layers: 0
  lr: 0.001
  max_epochs: 1
  max_text_length: -1
  name: multitask
  optimizer: Adam
  path: models/bert_multitask
  progress_bar: false
  sample: 256
  seed: 20
  task_layers: 1
  tokenizer: BERT
model_hparams: {}
model_name: multitask
optimizer_hparams:
  lr: 0.001
optimizer_name: Adam
